#!/bin/bash
# Script to launch the genxword crossword generator.
# Make sure that the path is correct.
# It might be different on your system.

# For archlinux
exec python2 /usr/lib/python2.7/site-packages/gencrossword/gencrossword.py $@

# For ubuntu and debian
#exec python2 /usr/lib/python2.7/dist-packages/gencrossword/gencrossword.py $@
