.TH GENXWORD-GTK 1 "17/5/2014" "Version 1.0.9" "User Commands"
.SH NAME
genxword-gtk \- a crossword generator
.SH SYNOPSIS
genxword-gtk
.SH DESCRIPTION
Genxword-gtk is a crossword generator, which produces pdf (A4 or letter size) 
versions of the grid and clues, or png / svg versions of the crossword grid, 
together with a text file containing the words and clues.
The word list that is used to create the crossword is also saved as a text file.
.PP
The word list can be created when using genxword-gtk, or it can be a text file 
that has already been written. It can contain words and clues, or just words.
Each word, or word and clue, should be on a separate line, and there should 
be a space between the word and clue. In the following example, the word is 'excalibur'
and the clue is 'The sword that a moistened bint lobbed at Arthur':
.TP
.PP
excalibur The sword that a moistened bint lobbed at Arthur.
.PP
Example word lists can be found in the /usr/share/genxword/word_lists/ directory.
.PP
There is also an option to sort the word list by word length, which might be useful 
when editing a long word list. This option also removes words with non-alphabetic characters.
.SH SEE ALSO
https://github.com/riverrun/genxword
.SH BUGS
No known bugs.
.SH AUTHOR
This program has been developed by David Whitlock (alovedalongthe@gmail.com), and it is based on a program originally written by Bryan Helmig. 
