.TH GENXWORD 1 "17/5/2014" "Version 1.0.9" "User Commands"
.SH NAME
genxword \- a crossword generator
.SH SYNOPSIS
genxword [\-a] [\-m] [\-n] [\-o] infile saveformat
.SH DESCRIPTION
genxword is a crossword generator which runs from the command line. There is 
also a version with a graphical user interface, which is called genxword-gtk.
It reads words and clues, or just words, from a text file and produces 
crosswords as pdf files, with the clues, and/or png/svg files, together 
with a text file containing the word bank and clues.
.PP
The infile is a text file containing words and clues, or just words.
Each word, or word and clue, should be on a separate line, and there should 
be a space between the word and clue. In the following example, the word is 'excalibur'
and the clue is 'The sword that a moistened bint lobbed at Arthur':
.TP
.PP
excalibur The sword that a moistened bint lobbed at Arthur.
.PP
Example word lists can be found in the /usr/share/genxword/word_lists/ directory.
.PP
Saveformat refers to the file format that you want the crossword saved as.
You can save it as an A4 size pdf (p), letter size pdf (l), or you can save 
the image files as png (n) and/or svg (s) files. If you choose to save the files in 
png/svg format, the word bank and clues will be saved in a text file.
.SH OPTIONS
.TP
\-a, \-\-auto
Run genxword non-interactively. Use this option if you want to run the program via a script.
If you use this option, the grid will be made larger and the crossword recalculated
until the crossword uses 90% or more of the words supplied.
.TP
\-n, \-\-number
The number of words to be used from the word list file, which can contain thousands 
of words. The default number is 50.
.TP
\-o, \-\-output
The name of the crossword. If you save the crossword as a pdf file, this name will be used as the title of the crossword.
.TP
\-m, \-\-mix
In this mode each clue will be an anagram of the word.
.TP
\-h, \-\-help
Print basic information about how to use the program.
.SH EXAMPLES
.TP
Create a crossword using the word_list.txt file and save it as an A4 size pdf.
.B genxword word_list.txt p
.TP
Create a crossword using 40 words from the word_list.txt file and save the grid and key in \
png and svg format, together with a text file containing the word bank and clues.
.B genxword \-n 40 word_list.txt ns
.TP
Create a crossword called "Norwegian_Blue" using non-interactive mode with words from the word_list.txt file \
and save it as a letter size pdf file.
.B genxword \-a \-o "Norwegian_Blue" word_list.txt l
.SH SEE ALSO
https://github.com/riverrun/genxword
.SH BUGS
No known bugs.
.SH AUTHOR
This program has been developed by David Whitlock (alovedalongthe@gmail.com), and it is based on a program originally written by Bryan Helmig. 
